apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.8
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: pgdb-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir:
